module VerifyExamples.PuzzleScript.Rule.Into0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import PuzzleScript.Rule exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#into: \n\n    \"player\" |> into \"star\"\n    --> ( Just \"player\", Just \"star\" )" <|
        \() ->
            Expect.equal
                (
                "player" |> into "star"
                )
                (
                ( Just "player", Just "star" )
                )