module VerifyExamples.PuzzleScript.Rule.Touching0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import PuzzleScript.Rule exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#touching: \n\n    [ constant \"fire\", \"tree\" |> into \"fire\" ]\n      |> touching\n      |> fromPattern\n      |> toString\n    --> \"[ fire | tree ] -> [ fire | fire ]\"" <|
        \() ->
            Expect.equal
                (
                [ constant "fire", "tree" |> into "fire" ]
                  |> touching
                  |> fromPattern
                  |> toString
                )
                (
                "[ fire | tree ] -> [ fire | fire ]"
                )